// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyhnbmexusojuyrikxfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aG5ibWV4dXNvanV5cmlreGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MzQ0NTAsImV4cCI6MjA3NTUxMDQ1MH0.3EvOeeWomHshBDFt0pnClT-QRDRpVRIjVeJYRSkl4gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});